/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import model.Atributo;
import report.ReporteNoImpl;

/**
 *
 * @author William Duarte
 */
public class GUIReporte extends javax.swing.JFrame {

    private ConexionBD conn;
    private ArrayList<Atributo> elements;
    private ArrayList<Atributo> obtenidos;
    
    /**
     * Creates new form GUIReporte
     */
    public GUIReporte(ConexionBD ref) {
        try {
            initComponents();
            conn = ref;
            generarTablas();
        } catch (SQLException ex) {
            Logger.getLogger(GUIReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void generarTablas() throws SQLException
    {       
        String cad = "SELECT table_name FROM user_tables";
        ResultSet rs = conn.executeQueryStatement(cad);
        this.cbTabla.addItem("Seleccione una tabla");
        while(rs.next())
        {
            this.cbTabla.addItem(rs.getString(1));
        }
    }
    
    public void generarList(String pNomTabla) 
    {
        try {
            DefaultListModel<String> model = new DefaultListModel<>();
            elements = new ArrayList<>();
            String cad = "SELECT column_name, data_type, data_length FROM user_tab_cols WHERE table_name = '" + pNomTabla +"'";
            ResultSet rs = conn.executeQueryStatement(cad);
            while(rs.next())
            {
                Atributo x = new Atributo(rs.getString(1), rs.getString(2), rs.getInt(3));
                elements.add(x);
                model.addElement(x.getNombre());
                listTabla.setModel(model);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIReporte.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "ups mejodí.");
        }
    }
           
    public void obtenerElementos()
    {
        obtenidos = new ArrayList<>();
        int[] indices = listTabla.getSelectedIndices();
        
        
        for (int i = 0; i < elements.size(); i++) {
            for (int j = 0;  j < indices.length; j++) {
                if(i == indices[j])
                {
                    System.out.println(elements.get(i).getNombre()+ " "+elements.get(i).getTipoDato()+" "+elements.get(i).getLongitud());
                    obtenidos.add(elements.get(i));
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cbTabla = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTabla = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTablaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listTabla);

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(cbTabla, 0, 155, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(cbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTablaActionPerformed
        
        
        
    }//GEN-LAST:event_cbTablaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nomTabla = cbTabla.getSelectedItem().toString();
        System.out.println(nomTabla);
        generarList(nomTabla);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        for (int i = 0; i < elements.size(); i++) {
//            System.out.println(elements.get(i).getNombre()+ " "+elements.get(i).getTipoDato()+" "+elements.get(i).getLongitud());
//        }
        obtenerElementos();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listTabla;
    // End of variables declaration//GEN-END:variables
}
